### ISSUE TITLE
What is inner intended for?

### ISSUE THREAD

**Issue by tmcw** [jsdoc3/jsdoc3.github.com#145]
I'm implementing support for inner in documentation.js and I'm unfortunately very confused about how it is intended to be used.

So far:

* I haven't found any JavaScript concepts called 'inner' that it might map to
* The [documentation](http://usejsdoc.org/tags-inner.html) documents an static property being marked as `inner`. What does this mean?
* Do `inner` members exist when you create a new instance of a class, like instance members, or do they exist all the time, like static members?
* Is there something else I'm missing?

Thanks for any help!

**Comment by hegemonic** [comment]
The `@inner` tag identifies a symbol that's not exported by a class or module. Here's a example of a module with an inner class:

```js
/** @module foo */

/**
 * Some class.
 */
class MyClass {
    constructor() {}
}
```

In this example, you don't actually need to use the `@inner` tag on the class, because JSDoc automatically figures out that it's an inner symbol. It's mostly there for use in virtual doclets, like the [first example in the docs](http://usejsdoc.org/tags-inner.html).

Hope that helps!
